#!/usr/bin/perl

$len = @ARGV;
if($len != 1) {
    die "oh";
}

open my $original, "<", @ARGV[0];
open my $target, ">", @ARGV[0].".out";

while(<$original>) {
    print STDOUT $_;
    s/fred/Larry/ig;
    print $target $_;
}
