#!/usr/bin/perl
use feature qw(signatures state say);

sub greet($name) {
   state @last = ();
   if(@last != 0) {
        say("Hi $name! I've seen @last");
    } else {
        say("Hi $name! You are the first one here!");
    }
    
    push(@last, $name);
}

&greet("fred");
&greet("barney");
&greet("wilma");
