#!/usr/bin/perl
use feature qw(signatures);
use strict;

sub total(@vals) {
    chomp(@vals);
    my $total = 0;
    foreach my $v (@vals) {
        $total += $v;
    }
    return $total;
}

my @fred = qw{1 3 5 7 9};
my $fred_total = total(@fred);
print "The total of \@fred is $fred_total.\n";
my $user_total = total(<STDIN>);
print "The total of those number is $user_total.\n";
