#!/usr/bin/perl
use feature qw(signatures state say);

print "123456789".("0123456789") x 10 ."\n";

my $width = <STDIN>;
chomp($width);
my @in = <STDIN>;
chomp(@in);
foreach(@in) {
    printf "%${width}s\n", $_;
}
