#!/usr/bin/perl
use Data::Dumper;

sub data_for_path {
    my $path = shift;
    if (-f $path or -l $path) {
        return undef;
    }

    if(-d $path) {
        my %directory;
        opendir PATH, $path or die "Cannot opendir $path: $!";
        my @names = readdir PATH;
        closedir PATH;

        for my $name (@names) {
            next if $name eq '.' or $name eq '..';
            $directory{$name} = data_for_path("$path/$name");
        }
        return \%directory;
    }

    warn "$path is neither a file nor directory\n";
    return undef;
}

# print Dumper(data_for_path('/Users/inabajun/git/learning-perl'));
# dump_data_for_path('/Users/inabajun/git/learning-perl', data_for_path('/Users/inabajun/git/learning-perl'), 0);
print Dumper (data_for_path('/Users/inabajun/git/learning-perl/intermediate-perl/dir'));

sub dump_data_for_path {
    my $path = shift;
    my $data = shift;
    my $depth = shift;

    if(not defined $data) {
        print ' ' x ($depth * 2) . "$path\n";
        return;
    } else {
        my $l = keys %$data;
        if ($l == 0) {
            print ' ' x ($depth * 2) . "$path, an empty directory\n";
            return;
        } else {
            print ' ' x ($depth * 2) . "$path\n";
        }
    }

    foreach(sort keys %$data) {
        dump_data_for_path("$_", ${$data}{$_}, $depth+1);
    }
}