#!/usr/bin/perl
use Oogaboogoo::calendar qw(number_to_day_name number_to_month_name);

print number_to_day_name(1)."\n";
print number_to_day_name(7)."\n";
print number_to_month_name(1)."\n";
print number_to_month_name(12)."\n";
