#!/usr/bin/perl
use strict;
use warnings;

my %gilligan_info = (
	name     => 'Gilligan', 
	hat      => 'White', 
	shirt    => 'Red', 
	position => 'First Mate',
);
my %skipper_info = (
	name     => 'Skipper',
	hat      => 'Black',
	shirt    => 'Blue',
	position => 'Captain',
);

my %howell_info = (
	name     => 'Howell',
	hat      => 'Black',
	shirt    => 'Blue',
	position => 'Captain',
);

my @crew = (\%gilligan_info, \%skipper_info, \%howell_info);

foreach (@crew) {
	my $ref = $_;
	$$ref{address} = "The Island";
	if($$ref{name} eq "Howell") {
		$$ref{address} = "The Island Country Club";
	}
	printf "%s at %s\n", $$ref{name}, $$ref{address};
}
