#!/usr/local/bin/env perl
# use strict;
use warnings;
use feature qw(say);

{
    my @a = qw(a b c);
    my @b = qw(a b c);
    # both reference count are 1
    push @a, \@b;
    # @b reference count is 2(from @b and via @a)
    push @b, \@a;
    print \@a;
    @a = ();
    print \@a;
    say $b[3][0];
}
# why is @b reference count 0?
